player.png: $(wildcard player_*.png) Makefile
	montage player_01.png player_02.png player_03.png player_04.png player_05.png player_06.png player_05.png player_04.png player_03.png player_02.png \
	-tile x1 -background transparent -texture player_parts.png -geometry 128x256+0+0 player.png
